apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: backup
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: backup
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: backup
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${APP_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_SERVICE_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying backup pod
    labels:
      service: backup
    name: backup
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
        labels:
          name: ${APP_SERVICE_NAME}
          service: backup
        name: ${APP_SERVICE_NAME}
      spec:
        serviceAccount: backup
        containers:
        - capabilities: {}
          env: {}
          image: ${IMAGE}
          imagePullPolicy: Always
          name: ${APP_SERVICE_NAME}
          securityContext:
            privileged: true
          volumeMounts:
            - name: backup-data
              mountPath: /backup-data
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
        volumes:
        - hostPath:
            path: /storage/infra01/infra-backup
          name: backup-data
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ${APP_SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: backup:latest
parameters:
- description: Application service name
  displayName: Application service name
  name: APP_SERVICE_NAME
  required: true
  value: backup
- description: backup image
  name: IMAGE
  value: 172.30.67.249:5000/infra-backups/backup
  required: true
- description: The exposed hostname that will route to the pod
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
  required: true
  value: backupstatus.fhpaas.fasthosts.co.uk
