#!/bin/bash
set -e

# Make backups
ruby /backup_script.rb run

# Clean up old backups
python /backup-cleaner.py -r 1 -v

# Move backups off cluster
if [ "${OFF_CLUSTER_BACKUPS_ENABLED}" == 'true' ]; then
  /off-cluster-backup.sh
fi
