#!/bin/bash
set -e

log () {
  echo "$(date) - Log message: $1" >> /var/log/periodic_daily.log
}

# Make backups
log "Starting /backup_script.rb"
ruby /backup_script.rb run

# Clean up old backups
log "Clearing old backups /backup-cleaner.py"
python /backup-cleaner.py -r 1 -v

# Move backups off cluster
if [ ${OFF_CLUSTER_BACKUPS_ENABLED} ]; then
  log "Moving backups off cluster /off-cluster-backup.sh"
  /off-cluster-backup.sh
fi
